---
- name: Attempting to import openvpn@client tasks
  tags: openvpn-client
  become: true
  block:
    - import_tasks: openvpn_client.yml
    - import_tasks: openvpn_systemd.yml
  when: ansible_os_family == 'RedHat'
...
