---
- name: Attempting to overlay tun modules-load.d configuration
  lineinfile:
    create: true
    line: tun
    path: /etc/modules-load.d/tun.conf
    owner: root
    group: root
    mode: 0600
    state: present

- name: Attempting to overlay openvpn@client configuration
  no_log: true
  template:
    src: client.conf.j2
    dest: /etc/openvpn/client.conf
    owner: root
    group: openvpn
    mode: 0640
  register: openvpn_client_template
  notify: restart openvpn@client
  when: openvpn_client_options|length > 0

- name: Attempting to overlay openvpn@client username and password, if applicable
  no_log: true
  template:
    src: login.conf.j2
    dest: "{{ openvpn_client_options.auth_user_pass }}"
    owner: root
    group: openvpn
    mode: 0640
  notify: restart openvpn@client
  when:
    - openvpn_client_options.auth_user_pass is defined
    - openvpn_client_username is defined
    - openvpn_client_password is defined

- name: Attempting to overlay openvpn@client scripts, if applicable
  no_log: true
  template:
    src: script.j2
    dest: "{{ item.path }}"
    owner: root
    group: openvpn
    mode: "{{ item.mode|default(0750) }}"
  notify: restart openvpn@client
  with_items: "{{ openvpn_client_scripts }}"
  when:
    - item.base64 is defined
    - item.path is defined
    - openvpn_client_scripts|length > 0

- name: Attempting to overlay openvpn@client systemd override, if applicable
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/openvpn@client.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  notify: reload systemd
  when: openvpn_client_systemd|length > 0
...
