---
- name: Ensure that the openvpn package is installed
  yum:
   name: openvpn
   state: present
  register: openvpn_client_yum

- name: Attempting to overlay openvpn@client directory tree
  file:
    path: "{{ item }}"
    owner: root
    group: openvpn
    mode: 0750
    state: directory
  with_items:
    - /etc/openvpn
    - /etc/openvpn/client
  when: openvpn_client_yum is success

- name: Attempting to overlay openvpn@client scripts directory, if applicable
  no_log: true
  file:
    path: "{{ item.path|dirname }}"
    owner: root
    group: openvpn
    mode: 0750
    state: directory
  with_items: "{{ openvpn_client_scripts }}"
  when:
    - item.path is defined
    - openvpn_client_scripts is defined
    - openvpn_client_yum is success

- name: Attempting to overlay openvpn@client configuration
  no_log: true
  template:
    src: client.conf.j2
    dest: /etc/openvpn/client.conf
    owner: root
    group: openvpn
    mode: 0640
  notify: restart openvpn@client
  when: openvpn_client_yum is success

- name: Attempting to overlay openvpn@client username and password, if applicable
  no_log: true
  template:
    src: login.conf.j2
    dest: "{{ openvpn_client_options.auth_user_pass }}"
    owner: root
    group: openvpn
    mode: 0640
  notify: restart openvpn@client
  when:
    - openvpn_client_options.auth_user_pass is defined
    - openvpn_client_username is defined
    - openvpn_client_password is defined
    - openvpn_client_yum is success

- name: Attempting to overlay openvpn@client scripts, if applicable
  no_log: true
  template:
    src: script.j2
    dest: "{{ item.path }}"
    owner: root
    group: openvpn
    mode: "{{ item.mode|default(0750) }}"
  notify: restart openvpn@client
  with_items: "{{ openvpn_client_scripts }}"
  when:
    - item.base64 is defined
    - item.path is defined
    - openvpn_client_scripts is defined
    - openvpn_client_yum is success

- name: Ensure that openvpn@client is started and enabled on boot
  systemd:
    enabled: yes
    service: openvpn@client
    state: started
  when: openvpn_client_yum is success
...
