---
- name: Attempting to overlay openvpn@client systemd override directory, if applicable
  file:
    path: /etc/systemd/system/openvpn@client.service.d
    owner: root
    group: root
    mode: 0755
    state: directory
  when:
    - openvpn_client_systemd|length > 0
    - openvpn_client_yum is success

- name: Attempting to overlay openvpn@client systemd override, if applicable
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/openvpn@client.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  notify: reload systemd
  when:
    - openvpn_client_systemd|length > 0
    - openvpn_client_yum is success

- name: Ensure that openvpn@client is started and enabled on boot
  systemd:
    enabled: yes
    service: openvpn@client
    state: started
  when: openvpn_client_yum is success
...
