---
- name: Ensure that openvpn@client is started and enabled on boot
  service:
    enabled: yes
    service: openvpn@client
    state: started
  when:
    - openvpn_client_options|length > 0
    - openvpn_client_template is success
...
