---
- name: Attempting to overlay openvpn@client systemd override directory, if applicable
  file:
    path: /etc/systemd/system/openvpn@client.service.d
    owner: root
    group: root
    mode: 0755
    state: directory
  when: openvpn_client_systemd|length > 0

- name: Attempting to overlay openvpn@client systemd override, if applicable
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/openvpn@client.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart openvpn-client
  when: openvpn_client_systemd|length > 0
...
