---
- name: restart openvpn-client
  tags: openvpn-client
  become: true
  systemd:
    service: openvpn@client
    state: restarted

- name: reload systemd
  tags: openvpn-client
  become: true
  systemd:
    daemon_reload: yes
...
